import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/About.module.scss'
import { faBars } from '@fortawesome/free-solid-svg-icons'
import MobileNav from '../components/MobileNav'
import { useContext } from "react";
import AppContext from '../components/AppContext'

const About = () => {
  let { language, languageFnEs, languageFnEn } = useContext(AppContext)

  const [mobileNav, setMobileNav] = useState(false)
  const mobileNavFn = () => {
    setMobileNav(!mobileNav)
  }

  if (typeof window !== "undefined") {
    mobileNav ? document.body.style.overflow = "hidden" : document.body.style.overflow = 'auto'
  }


  return (
    <div className={styles.about}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../" />
      </Head>
      <div className={styles.languageBtns}>
        <button className={styles.languageBtn} onClick={languageFnEs}>ES</button>
        <p>/</p>
        <button className={styles.languageBtn} onClick={languageFnEn}>EN</button>
      </div>

      <div className={`${styles.mobileNav__container}`}>
        <MobileNav parent='about' mobileNavFn={mobileNavFn} mobileNavState={mobileNav} language={language} />
      </div>

      <button className={styles.burgerBtn} onClick={mobileNavFn}>
        <FontAwesomeIcon icon={faBars} className={styles.burger} />
      </button>



      <h1 className={styles.title}>Hola, soy Soledad y soy la creadora de Polo & Wine.</h1>
    </div>
  )
}

export default About