import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Events.module.scss'
import { faBars } from '@fortawesome/free-solid-svg-icons'
import MobileNav from '/components/MobileNav/MobileNav'
import { useContext } from "react";
import AppContext from '../components/AppContext'
import Contacto from '../components/Contacto/Contacto'
import Nav from '../components/Nav/Nav'

const Events = () => {
  let { language, languageFnEs, languageFnEn } = useContext(AppContext)

  const [mobileNav, setMobileNav] = useState(false)
  const mobileNavFn = () => {
    setMobileNav(!mobileNav)
  }

  if (typeof window !== "undefined") {
    mobileNav ? document.body.style.overflow = "hidden" : document.body.style.overflow = 'auto'
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Polo & Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Nav language={language} />
      <div className={styles.languageBtns}>
        <button className={styles.languageBtn} onClick={languageFnEs}>ES</button>
        <p>/</p>
        <button className={styles.languageBtn} onClick={languageFnEn}>EN</button>
      </div>
      <div className={`${styles.mobileNav__container}`}>
        <MobileNav parent='events' mobileNavFn={mobileNavFn} mobileNavState={mobileNav} language={language} />
      </div>

      <button className={styles.burgerBtn} onClick={mobileNavFn}>
        <FontAwesomeIcon icon={faBars} className={styles.burger} />
      </button>

      <section>
        <div className={styles.separador}></div>
        <div className={styles.event}>
          <h2 className={styles.eventTitle}>POLO EXPERIENCE ARGENTINA</h2>
          <p className={styles.eventText}>Polo&Wine te invita a disfrutar de una experiencia 100% argentina que combina naturaleza, gastronomía y lo mejor del polo. <br /><br />A tan solo 50 minutos de Buenos Aires, te espera una aventura inolvidable en la que <span> conocerás la historia del polo, asistirás a partidos en tiempo real y disfrutarás de un día de campo rodeado de caballos de primera categoría y jinetes expertos.</span><br /><br />Ya sea que quieras tomar lecciones de polo, convertirte en jugador por un día o disfrutar de un partido bajo la luz de la luna, te ofrecemos una<span>selección de programas exclusivos durante los 365 días del año.</span> <br /><br />Te invitamos a conocer nuestras propuestas.</p>

          <div className={styles.card}>
            <div className={styles.cardContainer1}>
              <h3 className={styles.cardTitle}>Polo Day</h3>
              <p className={styles.cardText}>El Polo Day es un programa pensado para todos aquellos que <span>quieren ser polistas por un día y aprender los secretos del deporte más exclusivo de Argentina.</span> <br />
                Nuestra propuesta incluye capacitaciones, asistencia a partidos de polo en vivo, clases de polo, cabalgatas por la Estancia La Carona y degustación de lo mejor de la gastronomía local.<br /><br />
                ● Horario: 9:00 h a 5:00 h<br />
                ● Incluye: Recepción, clases, mini partido, almuerzo y café.</p>
            </div>

            <a href='https://wa.link/jdmx80' rel='noreferrer' target="_blank" className={styles.cardBtn}>Consultar</a>

          </div>
          <div className={styles.card}>
            <div className={styles.cardContainer1}>
              <h3 className={styles.cardTitle}>Polo Holiday</h3>
              <p className={styles.cardText}>El Polo Holiday es el evento ideal para <span>aficionados o jugadores profesionales que quieren combinar sus vacaciones con programas de polo de más de 1 día de duración.</span> <br /> <br />
                ● Horario: 9:00 am a 5:00 pm <br />
                ● Incluye: lecciones de polo, alojamiento, desayuno, almuerzo y cena.</p>
            </div>
            <a href='https://wa.link/jdmx80' rel='noreferrer' target="_blank" className={styles.cardBtn}>Consultar</a>
          </div>
          <div className={styles.card}>
            <div className={styles.cardContainer1}>
              <h3 className={styles.cardTitle}>Polo Night</h3>
              <p className={styles.cardText}>El Polo Night es un evento pensado para quienes quieren <span>disfrutar de una experiencia de polo memorable bajo la luz de la luna.</span> <br />
                La propuesta consiste en presenciar un partido en la única cancha profesional iluminada del mundo, mientras se degusta una típica “picada” argentina, acompañada por empanadas, sandwiches gourmet de carne asada y un exclusivo vino nacional.<br /><br />
                ● Horario: 5:00 pm a 9:30 pm<br />
                ● Incluye: Recepción, clases, partido y cena.</p>
            </div>
            <a href='https://wa.link/jdmx80' rel='noreferrer' target="_blank" className={styles.cardBtn}>Consultar</a>
          </div>

        </div>

        <div className={styles.separador}></div>
        <div className={styles.event}>
          <h2 className={styles.eventTitle}>PREMIER LEAGUE INGLATERRA</h2>
          <p className={styles.eventText}>Vive lo mejor de la Premier League y descubre el ambiente vibrante de ciudades como Liverpool, Manchester o Londres.<br /><br /><span>La Premier League de Inglaterra es la liga más emocionante del mundo</span> y para muchos fanáticos del fútbol, ver un partido en vivo y en directo es una oportunidad única en la vida.<br /><br />The Premiership, como le llaman en Inglaterra, se destaca no solo por su nivel competitivo en aumento, sino también por <span> el ambiente tan característico de sus estadios y por la mística de los aficionados que pueblan sus gradas en cada encuentro.</span><br /><br />Célebres equipos como el Chelsea, el Manchester United, el Liverpool o el Tottenham le dan vida a esta competencia británica que cuenta con millones de espectadores y fanáticos en todo el mundo.<br /><br />Polo & Wine te invita a <span>disfrutar de la máxima categoría del futbol inglés y a presenciar los mejores partidos en estadios legendarios como Anfield Road, Old Trafford o Stamford Bridge.</span><br /><br />Ya sea que quieras ser testigo del gran derby entre el Liverpool y el Manchester City o hacer coincidir tu escapada a Londres con una visita al Emirates Stadium, <span>tenemos el programa perfecto para ti.</span> <br /><br />Elige uno o varios partidos de tu equipo favorito y deja que nosotros nos ocupemos del resto. <span>Somos especialistas en Turismo Deportivo y de Eventos, diseñamos viajes a medida y nos adaptamos a tu presupuesto y necesidades.</span><br /><br />Si eres un verdadero amante del fútbol, no puedes perderte la oportunidad de vibrar con el ambiente único que se respira en un campo de fútbol inglés.<br /><br />Consúltanos por las fechas de salida y el calendario temporada 2022/2023 de la Premier League.</p>

          <div className={styles.card}>
            <p className={styles.cardText}>Servicios Incluidos:<br />
              ● Selección de hoteles de 3, 4, o 5 estrellas<br />
              ● Traslados in/out<br />
              ● Asesoramiento y asistencia bilingüe durante todo el viaje<br />
              ● Servicios sujetos a disponibilidad en el momento de realizar la reserva<br />
              ● Consultar por otros servicios de este paquete</p>
            <a href='https://wa.link/jdmx80' rel='noreferrer' target="_blank" className={styles.cardBtn}>Consultar</a>
          </div>
        </div>

        <div className={styles.separador}></div>
        <div className={styles.event}>
          <h2 className={styles.eventTitle}>WIMBLEDON 2023</h2>
          <p className={styles.eventText}>Disfruta en vivo y en directo de Wimbledon, el certamen de tenis más antiguo del mundo y vive la mejor experiencia de Grand Slam.<br /><br />

            Cada año, la ciudad de Londres recibe a los mejores tenistas del mundo y cientos de aficionados se dan cita en el coqueto barrio de Wimbledon para ser testigos del torneo más prestigioso de tenis a nivel mundial.<br /><br />

            Ya sea que quieras asistir al legendario evento y disfrutar del ambiente festivo de la ciudad o aprovechar el viaje para recorrer Londres y sus alrededores,<span> tenemos el programa perfecto para ti.</span><br /><br />

            <span>Polo & Wine te invita a disfrutar de Wimbledon 2023 en Londres. Escoge las fechas de los partidos y deja que nosotros nos ocupemos del resto.</span><br /><br />

            Somos especialistas en Turismo Deportivo y de Eventos y nos encargamos de organizar tu viaje a Wimbledon completamente a medida para que disfrutes del único Grand Slam sobre hierba.<br /><br />

            Además, si quieres planificar días adicionales para recorrer otras ciudades del Reino Unido, te ofrecemos<span> alternativas para realizar turismo local y reservamos las mejores excursiones y paseos para que viajes tranquilo y de la mejor manera posible.</span><br /><br />

            Si eres fanático de este deporte, no te pierdas la oportunidad de conocer la “Catedral del Tenis” y saborear las tradicionales frutillas con crema de Wimbledon. ¡Sin dudas es una experiencia que no debes dejar pasar!<br /><br />

            <span>Empieza a planificar tu viaje a Wimbledon para el 2023 y reserva con Polo & Wine todos los servicios.</span><br /><br />

            Consúltanos por las fechas de salida y todos los paquetes disponibles para ver el torneo de Wimbledon en Londres.
          </p>

          <div className={styles.card}>
            <p className={styles.cardText}>Servicios Incluidos:<br />
              ● Selección de hoteles de 3, 4, o 5 estrellas<br />
              ● Traslados in/out<br />
              ● Asesoramiento y asistencia bilingüe durante todo el viaje<br />
              ● Servicios sujetos a disponibilidad en el momento de realizar la reserva<br />
              ● Consultar por otros servicios de este paquete
            </p>
            <a href='https://wa.link/jdmx80' rel='noreferrer' target="_blank" className={styles.cardBtn}>Consultar</a>
          </div>
        </div>

        <div className={styles.separador}></div>
        <div className={styles.event}>
          <h2 className={styles.eventTitle}>TOMORROWLAND 2023</h2>
          <p className={styles.eventText}>Disfruta de Tomorrowland, el festival de música electrónica más potente del mundo, y vive una experiencia que no olvidarás jamás.<br /><br />

            Cada año, miles de fanáticos viajan a Boom, una pequeña localidad belga entre Amberes y Bruselas, para presenciar este espectáculo musical que reúne lo mejor de la música dance y electrónica.<br /><br />

            Durante casi una semana, más de 50000 viajeros de todas partes del mundo se dan cita en este gran parque temático que cuenta con más de 15 escenarios diferentes y en el que cientos de artistas salen a escena durante cada jornada.<br /><br />

            Ya sea que quieras acampar en la Dreamville, el sector de campings dentro del predio de Tomorrowland, o prefieras la comodidad y tranquilidad de un hotel cercano al festival, <span>tenemos el programa perfecto para ti.</span> <br /><br />

            Somos especialistas en Turismo Deportivo y de Eventos y nos encargamos de organizar tu viaje a Tomorrowland completamente a medida para que disfrutes del festival y sus momentos más icónicos.<br /><br />

            Además, si quieres planificar días adicionales para recorrer otras ciudades de Bélgica, te ofrecemos <span>alternativas para realizar turismo local y reservamos las mejores excursiones y paseos para que viajes tranquilo y de la mejor manera posible.</span><br /><br />

            Empieza a planificar tu viaje a Tomorrowland 2023 y reserva con Polo & Wine todos los servicios. <br /><br />

            Consúltanos por todos los paquetes disponibles para asistir a Tomorrowland 2023 en Bélgica y sumérgete en la atmósfera única del festival de música dance más grande del mundo.</p>


          <div className={styles.card}>
            <p className={styles.cardText}>Servicios Incluidos:<br />
              ● Alojamiento en carpas en la Dreamville o en hoteles ubicados en zonas cercanas al predio<br />
              ● Traslados in/out<br />
              ● Asesoramiento y asistencia bilingüe durante todo el viaje<br />
              ● Servicios sujetos a disponibilidad en el momento de realizar la reserva<br />
              ● Consultar por otros servicios de este paquete
            </p>
            <a href='https://wa.link/jdmx80' rel='noreferrer' target="_blank" className={styles.cardBtn}>Consultar</a>
          </div>
        </div>
      </section>

      <Contacto />

    </div>
  )
}

export default Events