import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Presentacion from '../components/Presentacion'
import styles from '../styles/Home.module.css'
import { useContext } from "react";
import AppContext from '../components/AppContext'
import EventosHome from '../components/EventosHome'
import NuestrosServicios from '../components/NuestrosServicios'
import Confiar from '../components/Confiar'
import Pilares from '../components/Pilares'
import Testimonios from '../components/Testimonios'
import Numeros from '../components/Numeros'
import ComoTrabajamos from '../components/ComoTrabajamos'
import Contacto from '../components/Contacto'

export default function Home() {
  const value = useContext(AppContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../" />
      </Head>
      <Hero languageObj={value} />
      <Presentacion language={value.language} />
      <EventosHome language={value.language} />
      <NuestrosServicios language={value.language} />
      <Confiar language={value.language} />\
      <Pilares language={value.language} />
      <Testimonios language={value.language} />
      <Numeros language={value.language} />
      <ComoTrabajamos language={value.language} />
      <Contacto language={value.language} />
    </div>
  )
}
