import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Presentacion from '../components/Presentacion'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../" />
      </Head>
      <Hero />
      <Presentacion />
    </div>
  )
}
