import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/homepage/Hero/Hero'
import Presentacion from '../components/homepage/Presentacion/Presentacion'
import styles from '../styles/Home.module.css'
import { useContext } from "react";
import AppContext from '../components/AppContext'
import EventosHome from '../components/homepage/EventosHome/EventosHome'
import NuestrosServicios from '../components/homepage/NuestrosServicios/NuestrosServicios'
import Confiar from '../components/homepage/Confiar/Confiar'
import Pilares from '../components/homepage/Pilares/Pilares'
import Testimonios from '../components/homepage/Testimonios/Testimonios'
import Numeros from '../components/homepage/Numeros/Numeros'
import ComoTrabajamos from '../components/homepage/ComoTrabajamos/ComoTrabajamos'
import Contacto from '../components/Contacto/Contacto'
import Nav from '../components/Nav/Nav'

export default function Home() {
  const value = useContext(AppContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Polo & Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Nav language={value.language} />
      <Hero languageObj={value} />
      <Presentacion language={value.language} />
      <EventosHome language={value.language} />
      <NuestrosServicios language={value.language} />
      <Confiar language={value.language} />\
      <Pilares language={value.language} />
      <Testimonios language={value.language} />
      <Numeros language={value.language} />
      <ComoTrabajamos language={value.language} />
      <Contacto language={value.language} />
    </div>
  )
}
